---
fixtures:
    repositories:
        stdlib:
          ref: "4.12.0"
          repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
        resolv_conf:
          ref: "v3.0.5"
          repo: "https://github.com/saz/puppet-resolv_conf"
        apt:
          ref: "2.2.2"
          repo: "https://github.com/puppetlabs/puppetlabs-apt"

    symlinks:
        vision_default: '#{source_dir}'
