---
fixtures:
  repositories:
    stdlib:
      ref: "4.25.1"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    apt:
      ref: "5.0.1"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    unattended_upgrades:
      ref: "v4.0.0"
      repo: "https://github.com/voxpupuli/puppet-unattended_upgrades"
    vision_groups:
      repo: "https://github.com/vision-it/vision-groups"
      ref: "origin/production"
    augeasproviders_core:
      repo: "https://github.com/hercules-team/augeasproviders_core"
      ref: "2.1.3"
    augeasproviders_sysctl:
      repo: "https://github.com/hercules-team/augeasproviders_sysctl"
      ref: "2.1.0"
  symlinks:
    vision_default: '#{source_dir}'
