---
fixtures:
    repositories:
        stdlib:
          ref: "4.12.0"
          repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
        resolv_conf:
          ref: "v3.0.5"
          repo: "https://github.com/saz/puppet-resolv_conf"
        apt:
          ref: "2.2.2"
          repo: "https://github.com/puppetlabs/puppetlabs-apt"
        vision_shells:
          ref: "origin/production"
          repo: "https://github.com/vision-it/vision-shells"
        ohmyzsh:
          ref: "v1.0.4"
          repo: "https://github.com/zanloy/puppet-ohmyzsh"
        vision_groups:
          repo: "https://github.com/vision-it/vision-groups"
          ref: "origin/production"
        augeasproviders_core:
          repo: "https://github.com/hercules-team/augeasproviders_core"
          ref: "2.1.3"
        augeasproviders_sysctl:
          repo: "https://github.com/hercules-team/augeasproviders_sysctl"
          ref: "2.0.2"
    symlinks:
        vision_default: '#{source_dir}'
