---
fixtures:
  repositories:
    stdlib:
      ref: "v6.2.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    apt:
      ref: "v7.1.0"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    host_core:
      ref: "1.0.2"
      repo: "https://github.com/puppetlabs/puppetlabs-host_core"
    mailalias_core:
      ref: "1.0.6"
      repo: "https://github.com/puppetlabs/puppetlabs-mailalias_core"
    unattended_upgrades:
      ref: "v4.0.0"
      repo: "https://github.com/voxpupuli/puppet-unattended_upgrades"
    ntp:
      ref: "v8.3.0"
      repo: "https://github.com/puppetlabs/puppetlabs-ntp"
    vision_groups:
      repo: "https://github.com/vision-it/vision-groups"
      ref: "origin/production"
  symlinks:
    vision_default: '#{source_dir}'
